application: addressbook
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/images
  static_dir: static/images

- url: /static/js
  static_dir: static/js

- url: /static
  static_dir: static
  mime_type: text/cache-manifest

- url: .*
  static_files: index.htm
  upload: index.html
  mime_type: text/html
